version: '2.4'

networks:
  internal:
  web:
    external:
      name: pazh-web-proxy

x-srv:
  &pazh-srv

  networks:
    - internal

  restart: unless-stopped
  tty: true

  # cpus: 0.5
  # cpuset: '0'
  cpu_shares: 1024
  mem_limit: 1g
  # memswap_limit: 2g

  # ulimits:
  #   nproc: 65535
  #   nofile:
  #     soft: 49999
  #     hard: 99999

  logging:
    driver: json-file
    options:
      max-size: '12m'
      max-file: '2'

x-labels:
  &pazh-labels
  pazh.project: $PROJECT
  pazh.domain:  $DOMAIN_PWA
  pazh.version: 'v2.0.0'

services:
  pwa:
    << : *pazh-srv
    build: .
    hostname: $DOMAIN_PWA # set to fqdn of host
    networks:
      - web
    labels:
      << : *pazh-labels
      traefik.enable: true
      traefik.backend: ${PROJECT}
      traefik.port: 8080
      traefik.frontend.rule: Host:${DOMAIN_PWA}
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https

  api:
    << : *pazh-srv
    image: strapi/strapi # https://hub.docker.com/r/strapi/strapi
    networks:
      - internal
      - web
    depends_on:
      - database

    volumes:
      - type: bind
        source: ./api
        target: /usr/src/api/$PROJECT


    environment:
      APP_NAME: $PROJECT
      HOST: 0.0.0.0
      DATABASE_CLIENT: mongo
      DATABASE_HOST: database
      DATABASE_PORT: 27017
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_AUTHENTICATION_DATABASE: $DATABASE_NAME
      #DATABASE_SSL: false
      #DATABASE_SRV: false

    labels:
      << : *pazh-labels
      traefik.enable: true
      traefik.backend: ${PROJECT}-api
      traefik.port: 1337
      traefik.frontend.rule: Host:${DOMAIN}
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https

  database:
    << : *pazh-srv
    image: mongo
    networks:
      - internal

    volumes:
      - type: bind
        source: ./_data/database
        target: /data/db

    environment:
      MONGO_INITDB_DATABASE: $DATABASE_NAME
      MONGO_INITDB_ROOT_USERNAME: $DATABASE_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DATABASE_PASSWORD
